package View;

import Model.CentroComercial.CentroComercial;
import Model.Cliente.Cliente;
import Model.Tienda.Tienda;
import Patrones.Iterator.Iterator;
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author rafa_
 */
public class CentroComercialView extends javax.swing.JFrame {

    private CentroComercial centroComercial;
    private Cliente cliente;

    /**
     * Creates new form MenuPrincipal
     */
    public CentroComercialView(CentroComercial centroComercial, Cliente cliente) {
        this.setResizable(false);

        this.centroComercial = centroComercial;
        this.cliente = cliente;

        initComponents();
        this.setLocationRelativeTo(null);

        //Inicialización de los elementos de la vista.
        nombreCentroComercialLabel.setText(centroComercial.getNombre());
        nombreClienteLabel.setText("Has ingresado como: " + cliente.getNombre());
        pagarCarritoComprasButton.setEnabled(false);
        eliminarCarritoComprasButton.setEnabled(false);
        ingresarTiendaButton.setEnabled(false);
        notificacionesTable.setEnabled(false);
        
        mostrarTiendas();
        mostrarNotificaciones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        tiendasScrollPane = new javax.swing.JScrollPane();
        tiendasTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        solicitarCarritoComprasButton = new javax.swing.JButton();
        pagarCarritoComprasButton = new javax.swing.JButton();
        ingresarTiendaButton = new javax.swing.JButton();
        notificacionesScrollPane = new javax.swing.JScrollPane();
        notificacionesTable = new javax.swing.JTable();
        eliminarCarritoComprasButton = new javax.swing.JButton();
        nombreClienteLabel = new javax.swing.JLabel();
        instruccionesLabel = new javax.swing.JLabel();
        salirButton = new javax.swing.JButton();
        nombreCentroComercialLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(252, 86, 50));

        tiendasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tiendas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tiendasTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tiendasTableMouseClicked(evt);
            }
        });
        tiendasScrollPane.setViewportView(tiendasTable);

        jLabel3.setBackground(new java.awt.Color(252, 86, 50));
        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel3.setText("Carrito de compras");

        solicitarCarritoComprasButton.setText("Solicitar carrito de compras");
        solicitarCarritoComprasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solicitarCarritoComprasButtonActionPerformed(evt);
            }
        });

        pagarCarritoComprasButton.setText("Ver/Pagar carrito de compras");
        pagarCarritoComprasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagarCarritoComprasButtonActionPerformed(evt);
            }
        });

        ingresarTiendaButton.setText("Ingresar a tienda");
        ingresarTiendaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarTiendaButtonActionPerformed(evt);
            }
        });

        notificacionesTable.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        notificacionesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Notificaciones"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        notificacionesScrollPane.setViewportView(notificacionesTable);

        eliminarCarritoComprasButton.setText("Eliminar carrito de compras");
        eliminarCarritoComprasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarCarritoComprasButtonActionPerformed(evt);
            }
        });

        nombreClienteLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        nombreClienteLabel.setText("Has ingresado como:");

        instruccionesLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        instruccionesLabel.setText("Seleccione una tienda y presione el botón \"Ingresar a tienda\":");

        salirButton.setText("Salir");
        salirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jLabel3)
                                .addGap(86, 86, 86))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(solicitarCarritoComprasButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pagarCarritoComprasButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eliminarCarritoComprasButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(72, 72, 72)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(notificacionesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreClienteLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(instruccionesLabel)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(salirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ingresarTiendaButton))
                                .addComponent(tiendasScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(nombreClienteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(notificacionesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(solicitarCarritoComprasButton)
                        .addGap(18, 18, 18)
                        .addComponent(pagarCarritoComprasButton)
                        .addGap(18, 18, 18)
                        .addComponent(eliminarCarritoComprasButton)))
                .addGap(10, 10, 10)
                .addComponent(instruccionesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(tiendasScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingresarTiendaButton)
                    .addComponent(salirButton))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        nombreCentroComercialLabel.setBackground(new java.awt.Color(252, 86, 50));
        nombreCentroComercialLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        nombreCentroComercialLabel.setForeground(new java.awt.Color(255, 255, 255));
        nombreCentroComercialLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreCentroComercialLabel.setText("Centro FMAT");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(nombreCentroComercialLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nombreCentroComercialLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 777, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 499, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(13, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(13, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pagarCarritoComprasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagarCarritoComprasButtonActionPerformed
        new CarritoComprasView(cliente, this).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_pagarCarritoComprasButtonActionPerformed

    private void ingresarTiendaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarTiendaButtonActionPerformed
        if (tiendaSeleccionadaIndex != -1 && cliente.getCarritoCompras() != null) {
            Iterator tiendasIterator = centroComercial.getTiendasIterator();
            
            int counter = 0;
            while (tiendasIterator.hasNext() && counter <= tiendaSeleccionadaIndex) {
                Tienda tienda = (Tienda) tiendasIterator.next();
                if (counter == tiendaSeleccionadaIndex) {
                    new TiendaView(tienda, cliente, this).setVisible(true);
                    break;
                }
                counter++;
            }
            
            setVisible(false);
        }
    }//GEN-LAST:event_ingresarTiendaButtonActionPerformed

    private void tiendasTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tiendasTableMouseClicked
        tiendaSeleccionadaIndex = tiendasTable.getSelectedRow();
        if (cliente.getCarritoCompras() != null && tiendaSeleccionadaIndex >= 0) {
            ingresarTiendaButton.setEnabled(true);
        } else {
            ingresarTiendaButton.setEnabled(false);
        }
    }//GEN-LAST:event_tiendasTableMouseClicked

    private void solicitarCarritoComprasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solicitarCarritoComprasButtonActionPerformed
        cliente.setCarritoCompras(centroComercial.getCarrito());
        pagarCarritoComprasButton.setEnabled(true);
        eliminarCarritoComprasButton.setEnabled(true);
        solicitarCarritoComprasButton.setEnabled(false);
        if (tiendaSeleccionadaIndex >= 0) {
            ingresarTiendaButton.setEnabled(true);
        } else {
            ingresarTiendaButton.setEnabled(false);
        }
    }//GEN-LAST:event_solicitarCarritoComprasButtonActionPerformed

    private void eliminarCarritoComprasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarCarritoComprasButtonActionPerformed
        centroComercial.cancelarCarrito(cliente);
        pagarCarritoComprasButton.setEnabled(false);
        eliminarCarritoComprasButton.setEnabled(false);
        ingresarTiendaButton.setEnabled(false);
        solicitarCarritoComprasButton.setEnabled(true);
    }//GEN-LAST:event_eliminarCarritoComprasButtonActionPerformed

    private void salirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirButtonActionPerformed
        centroComercial.salir(cliente);
        System.exit(0);
    }//GEN-LAST:event_salirButtonActionPerformed

    public CentroComercial getCentroComercial() {
        return centroComercial;
    }
    
    public void mostrarTiendas() {
        String tabla[][] = new String[centroComercial.getTiendas().size()][1];

        Iterator tiendasIterator = centroComercial.getTiendasIterator();
        int i = 0;
        while (tiendasIterator.hasNext()) {
            Tienda tienda = (Tienda) tiendasIterator.next();
            tabla[i][0] = tienda.getNombre();
            i++;
        }

        tiendasTable.setModel(new javax.swing.table.DefaultTableModel(
                tabla,
                new String[]{
                    "Tiendas",}
        ));
    }

    public void mostrarNotificaciones() {
        String tabla[][] = new String[cliente.getNotificaciones().size()][1];

        ArrayList<String> notificaciones = cliente.getNotificaciones();

        int j = 0;
        for (int i = notificaciones.size() - 1; i >= 0; i--) {
            tabla[j][0] = notificaciones.get(i);
            j++;
        }

        notificacionesTable.setModel(new javax.swing.table.DefaultTableModel(
                tabla,
                new String[]{
                    "Notificaciones",}
        ));
    }

    private int tiendaSeleccionadaIndex = -1;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton eliminarCarritoComprasButton;
    public javax.swing.JButton ingresarTiendaButton;
    public javax.swing.JLabel instruccionesLabel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel nombreCentroComercialLabel;
    public javax.swing.JLabel nombreClienteLabel;
    private javax.swing.JScrollPane notificacionesScrollPane;
    public javax.swing.JTable notificacionesTable;
    public javax.swing.JButton pagarCarritoComprasButton;
    public javax.swing.JButton salirButton;
    public javax.swing.JButton solicitarCarritoComprasButton;
    private javax.swing.JScrollPane tiendasScrollPane;
    public javax.swing.JTable tiendasTable;
    // End of variables declaration//GEN-END:variables
}
